---
- hosts: all 
  connection: ssh
  become: yes 
  become_method: sudo
  tasks:
    - name: Make decision on OS Types
      when: ansible_os_family == "RedHat"
      yum:
        name: httpd
        state: installed

    - name: Debian
      when: ansible_os_family == "Debian"
      apt:
        name: apache2
        state: installed
