---
- hosts: agent
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no 
  tasks:
    - name: Get the content of /etc/hosts
      command: cat /etc/hosts
      register: HOSTS
    - debug: msg="This is the content of /etc/hosts"
    - debug: msg="{{ HOSTS }}"
