---
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
    - name: Send template to remote system
      template:
         dest: /tmp
         src: /etc/ansible/myplaybooks/templates/index.html
         mode: 777
         owner: ansible
         group: ansible
